# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20171004_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
